# -*- coding: utf-8 -*-
"""
Created on Fri Jun 13 07:18:34 2025

@author: Admin
"""




from GPT_link import request
import json
import datetime
from information import cv_base

# Load your API key (replace this line with your preferred method)

if True:
    
    def summarize_rejections(jd,cv,rejection_comments,model = "gpt-5-mini"):
        space = 30*"-",
        line = f"""
    You are the legal counsel of a company responding to a claim from a former job applicant. 
    The applicant alleges they were rejected on an unfair basis.
    
    Important instructions:
    - Do NOT mention lawsuits, legal claims, or that this is a legal response. 
    - Write a professional, factual, and respectful explanation directed to the applicant.
    - Base your reasoning strictly on the information provided below.
    
    The input you will receive consists of:
    1. The job description of the position (first).
    2. The applicant’s CV (second).
    3. Written feedback from one or more recruiters (third, separated by {space}).
    
    Your task:
    - Extract the exact candidate name from the CV.
    - Write a clear, strong explanation of the rejection reasons, 
      showing where the applicant’s profile fell short of the role requirements.
    - Keep the explanation factual, detailed, and professional (maximum 10 sentences).
    - Do not add extra fields or commentary.
    
    Output format:
    Return the response strictly in JSON with the following structure:
    
    {{
      "candidate_name": "<exact candidate name from CV>",
      "reason_for_rejection": "<detailed explanation, up to 10 sentences>"
    }}
    
    Here is the job description:
    {jd}
    
    Here is the CV:
    {cv}
    
    Here is the list of recruiter feedback:
    {rejection_comments}
    """
    
        response = request(line,model=model)
        return response    
    
    
    def self_audit_rejection(jd,cv,legal_response,model = "gpt-5"):
        space = 30*"-",
        line = f"""
    You are acting as opposing counsel, tasked with auditing the rejection response given to a candidate. 
    Your role is to critically examine the JSON output provided by the company (the "response"). 
    
    Your goals are:
    1. Identify any weaknesses, inconsistencies, or vagueness in the reasoning.  
    2. Highlight any statements that appear unfair, discriminatory, or not supported by the job description, CV, or recruiter feedback.  
    3. Point out if the explanation goes beyond the evidence (e.g., hallucinated claims, assumptions not in source data).  
    4. Indicate if the explanation fails to clearly connect candidate shortcomings with the actual job requirements.  
    5. Flag if the JSON format is invalid or does not strictly follow the required structure.  
    
    The input you will receive consists of:
    - The job description  
    - The applicant’s CV  
    - Recruiter feedback (separated by {space})  
    - The JSON rejection response generated by the company  
    
    Your task:  
    - Write your audit in JSON format, structured as follows:  
    
    {{
      "audit_summary": "<overall assessment of the company’s response>",
      "unfair_or_discriminatory_points": ["<list of any potentially unfair points>"],
      "unsupported_or_hallucinated_points": ["<list of any claims not traceable to the sources>"],
      "format_issues": ["<list of any issues with JSON format or structure>"],
      "strength_of_reasoning": "<short assessment of whether the reasoning is strong, weak, or mixed, and why>"
    }}
    
    Here is the job description:
    {jd}
    
    Here is the CV:
    {cv}
    
    Here is the JSON rejection response to audit:
    {legal_response}
    """
        response = request(line,model=model)
        return response    
    
    def rebuttal_rejection(jd,cv,legal_response,legal_applicant,model = "gpt-5"):
        space = 30*"-",
        line = f"""
    You are the attorney representing the company. 
    Your task is to rewrite the company’s rejection response to the applicant, 
    taking into account the criticisms raised by the opposing counsel.  
    
    Important instructions:
    - Maintain the strict JSON output format (see structure below).
    - Keep the explanation professional, respectful, and factual.
    - Strengthen weak or vague reasoning identified by the opposing counsel.  
    - Remove or rephrase any points flagged as unfair, discriminatory, unsupported, or hallucinated.  
    - Ensure every reason is clearly tied to the job description, the applicant’s CV, or recruiter feedback.  
    - Keep the explanation concise but strong (maximum 10 sentences).  
    - Do not add commentary outside the JSON.
    
    Your output must follow this JSON structure exactly:
    
    {{
      "candidate_name": "<exact candidate name from CV>",
      "candidate_nationality":"<exact candidate name Nationality from CV or deduction>",
      "reason_for_rejection": "<corrected and strengthened explanation, up to 10 sentences>"
    }}
    
    The information provided to you:
    - Job description:  
    {jd}
    
    - Applicant CV:  
    {cv}
    
    
    - Original company response (to be revised):  
    {legal_response}
    
    - Opposing counsel’s audit of that response:  
    {legal_applicant}
    """
        response = request(line,model=model)
        return response    
    
    
    
    def summarize_texts(texts,model = "gpt-5"):
        line = """You must summarize these texts and condense them into 1.
                  These have all been generated by various LLM models for the same prompt.
                  In summary, the prompts were asking whether a candidate was suitable or not for a job position.
                  Summarize the texts clearly and without ommitting any of the given feedback to make sure no information justifying rejection or acceptation is missed.
                  These summary should be written in a way that does not give any chance of rebuttals by the candidates.
                  Each text will be separated by *******************"""
        for t in texts:
            line+="\n%s\n*******************\n"%t
        response = request(line,model=model)
        return response     
    
    def Analyse_job_offer(job_description,model = "gpt-4"):
        
        today = datetime.datetime.today()
        today = today.strftime("%d %m %Y")
        skills = ""
        ratings = ""
        prompt = f"""You are an expert in recruitment, job analysis, and skills extraction.
    Your task:
    1. Read the job description provided below.
    2. Identify exactly **10 broad key skills** required for the role — avoid overly detailed or niche skills.  
    3. Rank these skills from **most critical (rank 1)** to **least critical (rank 10)** for successfully performing the job.  
    4. Ensure the skills reflect both **technical** and **managerial/strategic** competencies where applicable.
    5. Output must be **strictly valid JSON**, following this exact format:
    
    {{
      "key_skills_ranked": [
        "Skill 1",
        "Skill 2",
        "Skill 3",
        "Skill 4",
        "Skill 5",
        "Skill 6",
        "Skill 7",
        "Skill 8",
        "Skill 9",
        "Skill 10"
      ]
    }}
    
    Formatting rules:
    - The output MUST contain only the JSON object — no explanations, no extra text.
    - Each skill must be a short phrase (max 6 words), capitalized as in a title.
    - No duplicate skills.
    - JSON must be directly parsable by Python’s json library without modifications.
    
    Now process the following job description and produce the ranked JSON list:
    
    [{job_description}]
    """
    
        # Send to ChatGPT
        response = request(prompt,model=model)
        return response 
    
    
    def Audit_layer_Skills(job_description,skills,model = "gpt-4"):
        skills_list = ""
        for s in skills:
            skills_list += s + ",\n"
        
        prompt = f"""You are an expert in recruitment, job analysis, and skills extraction. You are hired to perform a detailed audit of the previous groups of recruitment experts.
    Your task:
    1. Read the job description provided below.
    2. Various recruitment experts like you have selected a list of skills for this job offer, provided below as well 
    3. Out of these skills, ONLY, Identify exactly 10 required for the role — do not come back with any new skills.  
    4. Rank these skills from **most critical (rank 1)** to **least critical (rank 10)** for successfully performing the job.  
    5. Output must be **strictly valid JSON**, following this exact format:
    
    {{
      "key_skills_ranked": [
        "Skill 1",
        "Skill 2",
        "Skill 3",
        "Skill 4",
        "Skill 5",
        "Skill 6",
        "Skill 7",
        "Skill 8",
        "Skill 9",
        "Skill 10"
      ]
    }}
    
    Formatting rules:
    - The output MUST contain only the JSON object — no explanations, no extra text.
    - Each skill must be a short phrase (max 6 words), capitalized as in a title.
    - No duplicate skills.
    - JSON must be directly parsable by Python’s json library without modifications.
    
    Now process the following job description and produce the ranked JSON list:
    
    [{job_description}]
    
    and the skills provided.
    [{skills_list}]
    """
        # Send to ChatGPT
        response = request(prompt,model=model)
        return response 
    
    def compare_candidates_against_offer_chatgpt(cv_a, job_description, 
                                                 team_profile="", 
                                                 project_descriptions="",
                                                 model = "gpt-4",
                                                 categories = ["Technical Acumen","Team Leadership",
                                                 "Communication Skills","Relevant Experience",
                                                 "Complementarity with the existing team",
                                                 "Alignment with Ongoing & Future Projects"]):
        
        today = datetime.datetime.today()
        today = today.strftime("%d %m %Y")
        skills = ""
        ratings = ""
        for c in categories:
            skills+=" - %s \n"%c
            ratings+='\t"%s": grade from 0 to 10,\n'%c
        #ratings = ""
        prompt = f"""
    You are an impartial hiring assistant comparing one anonymized candidates for a specific role and long-term team fit, be harsh with candidates. Make sure only relevant people pass, yet make sure that it does not miss any relevant candidate.
    
    Do not consider data that is not relevant to the text being provided, analyse only the texts provided. 
    
    The date of Today is: \"\"\"{today}\"\"\"
    
    Your task is to:
    1. Compare the verify whether candidates could fit the job within these categories:
    {skills}
    2. Use both the job description and the list of ongoing/upcoming projects to determine what is most important.
    
    3. For each category:
       - Indicate what is the level of fit from 0 to 10
    
    4. Then, indicate clearly whether the candidate's CV is worth further review.
    
    5. Justify your overall decision in 5-7 clear, evidence-based sentences.
    
    Job Description:
    \"\"\"
    {job_description}
    \"\"\"
    
    Candidate:
    \"\"\"
    {cv_a}
    \"\"\"
    
    Team Profile:
    \"\"\"
    {team_profile}
    \"\"\"
    
    Ongoing and Upcoming Projects:
    \"\"\"
    {project_descriptions}
    \"\"\"
    
    Return the result in the following very strict JSON format:
    {{
      "Category rating": {{
    {ratings}
      }},
      "final_decision": "Yes" - "No" - "Maybe",
      "justification": "<Concise, evidence-based justification, especially referencing future team/project relevance>"
    }}
    """
    
        # Send to ChatGPT
        response = request(prompt,model=model)
        return response 
    
    
    def compare_candidates_chatgpt(cv_a, cv_b, job_description, team_profile="", 
                                   project_descriptions="",model = "gpt-4",
                                   categories = ["Technical Acumen","Team Leadership",
                                   "Communication Skills","Relevant Experience",
                                   "Complementarity with the existing team",
                                   "Alignment with Ongoing & Future Projects"]):
        skills = ""
        ratings = ""
        for c in categories:
            skills+=" - %s \n"%c
            ratings+='\t"%s": "A" | "B" | "Tie",\n'%c
        #ratings = ""
        
        prompt = f"""
    You are an impartial hiring assistant comparing two anonymized candidates for a specific role and long-term team fit.
    
    Your task is to:
    1. Compare the two candidates in each of the following categories:
    {skills}
    
    2. Use both the job description and the list of ongoing/upcoming projects to determine what is most important.
    
    3. For each category:
       - Indicate who is stronger, or if it is a tie.
    
    4. Then, choose the overall winner (or declare a tie) based on a balanced judgment of all six categories.
    
    5. Justify your overall decision in 5-7 clear, evidence-based sentences.
    
    Job Description:
    \"\"\"
    {job_description}
    \"\"\"
    
    Candidate A:
    \"\"\"
    {cv_a}
    \"\"\"
    
    Candidate B:
    \"\"\"
    {cv_b}
    \"\"\"
    
    Team Profile:
    \"\"\"
    {team_profile}
    \"\"\"
    
    Ongoing and Upcoming Projects:
    \"\"\"
    {project_descriptions}
    \"\"\"
    
    Return the result in the following very strict JSON format, do not add anything else, the justification comes at the end:
    {{
      "category_winners": {{
    {ratings}
      }},
      "overall_winner": "A" | "B" | "Tie",
      "justification": "<Concise, evidence-based justification, especially referencing future team/project relevance>"
    }}
    """
    
        # Send to ChatGPT
        response = request(prompt,model=model)
        return response 
        """
        # Attempt to load JSON safely
        try:
            result = json.loads(content)
        except json.JSONDecodeError:
            print("Warning: GPT response was not valid JSON. Raw response:")
            print(content)
            result = {"error": "Invalid JSON response", "raw": content}
    
        return result"""
    
    def candidate_background_check(cv,model = "gpt-5"):
        line = f"""You have been hired as a private investigator to investigate candidates backgrounds on line.
        you must search and provide as much relevant information that you can find.
        please also aknowledge that, while many people can be found on line, it is not always guaranteed that their profiles are up to date, so partial information is also acceptable, and does not mean they are lying. 
        You should confirm the following:
            - Employement history.
            - Studies hitory
            - Publications & Patents History
            - Check whether the companies mensionned on the CV are real or not. 
        with all this information, you can provide a report. 
        
        Here is the candidate's CV
        '{cv}'
        """

        response = request(line,model=model)
        return response     
       
    
    if __name__ == "__main__":
        if False:
            cv_a = """PhD in Aerospace, 7 years in CFD, 2 years in drone aeroelastic testing, Python, TensorFlow, Fluent."""
            cv_b = """MSc in Mechanical Engineering, 10 years in team leadership, PM on propulsion projects, skilled in communication."""
            
            job_description = """Seeking a propulsion lead with strong technical background in aerodynamics and the ability to manage cross-functional teams. CFD and data-driven diagnostics are a plus."""
            
            team_profile = """Current team has strong thermal and manufacturing expertise but lacks deep CFD and AI modeling."""
            
            project_descriptions = """1. AI turbine health monitoring. 2. CFD-based drone wing redesign. 3. Satellite structure FEM optimization."""
            
            result = compare_candidates_chatgpt(cv_a, cv_b, job_description, team_profile, project_descriptions,model="gpt-4.1-nano")
            
            print(json.dumps(result, indent=2))
        print("Start Search")
        test = candidate_background_check(cv_base)
        print("end Search")
        print(test)
